<?php

/**
 * Language translation editor.
 */

$checkSession = true;
require_once('../includes/library.php');

if ($_SESSION['profilSession'] != 0) {
    header('Location: ../general/permissiondenied.php');
    exit;
}

function language_editor_load($language)
{
    global $base_dir;

    $strings = array();
    $files = array(
        $base_dir . 'languages/lang_en.php',
        $base_dir . 'languages/global_en.php',
    );

    if ($language !== 'en') {
        $files[] = $base_dir . 'languages/lang_' . $language . '.php';
        $files[] = $base_dir . 'languages/global_' . $language . '.php';
    }

    foreach ($files as $file) {
        if (is_file($file) && is_readable($file)) {
            include $file;
        }
    }

    return is_array($strings) ? $strings : array();
}

function language_editor_save($language, $translations, &$saveError)
{
    global $base_dir;

    $languageDirectory = $base_dir . 'languages';
    $destination = $languageDirectory . '/global_' . $language . '.php';
    $temporary = tempnam($languageDirectory, '.language-');

    if ($temporary === false) {
        $saveError = 'Unable to create a temporary language file.';
        return false;
    }

    $content = "<?php\n\n/* Auto-generated by administration/edit_language.php. */\n\n";
    foreach ($translations as $key => $value) {
        $content .= '$strings[' . var_export((string) $key, true) . '] = ' . var_export((string) $value, true) . ";\n";
    }

    if (file_put_contents($temporary, $content, LOCK_EX) === false) {
        @unlink($temporary);
        $saveError = 'Unable to write the temporary language file.';
        return false;
    }

    if (!@rename($temporary, $destination)) {
        @unlink($temporary);
        $saveError = 'Unable to replace the language file. Check directory permissions.';
        return false;
    }

    return true;
}

$allowedLanguages = is_array($langValue) ? $langValue : array('en' => 'English');
$requestedLanguage = $_GET['language'] ?? $_POST['language'] ?? $lang ?? 'en';
$sellang = array_key_exists($requestedLanguage, $allowedLanguages) ? $requestedLanguage : 'en';
$pageSize = 100;
$offset = max(0, (int) ($_GET['offset'] ?? $_POST['offset'] ?? 0));
$notice = '';
$errorMessage = '';

if (empty($_SESSION['languageEditorToken'])) {
    $_SESSION['languageEditorToken'] = bin2hex(random_bytes(32));
}
$csrfToken = $_SESSION['languageEditorToken'];

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST') {
    $submittedToken = (string) ($_POST['csrf_token'] ?? '');
    if (!hash_equals($csrfToken, $submittedToken)) {
        $errorMessage = 'The form expired or is invalid. Reload the page and try again.';
    } else {
        $action = $_POST['action'] ?? '';
        $translations = language_editor_load($sellang);

        if ($action === 'save') {
            $submittedKeys = is_array($_POST['key'] ?? null) ? $_POST['key'] : array();
            $submittedValues = is_array($_POST['translation'] ?? null) ? $_POST['translation'] : array();
            foreach ($submittedKeys as $rowId => $key) {
                if (array_key_exists($key, $translations) && array_key_exists($rowId, $submittedValues)) {
                    $translations[$key] = (string) $submittedValues[$rowId];
                }
            }

            if (language_editor_save($sellang, $translations, $errorMessage)) {
                $notice = count($submittedKeys) . ' ' . text('translations_saved_ok');
            }
        } elseif ($action === 'delete') {
            $removeKeys = is_array($_POST['remove'] ?? null) ? $_POST['remove'] : array();
            $removed = 0;
            foreach ($removeKeys as $key) {
                if (array_key_exists($key, $translations)) {
                    unset($translations[$key]);
                    $removed++;
                }
            }

            if ($removed === 0) {
                $errorMessage = 'Select at least one translation to delete.';
            } elseif (language_editor_save($sellang, $translations, $errorMessage)) {
                $notice = $removed . ' ' . text('labels_deleted');
            }
        } elseif ($action === 'add') {
            $newLabel = trim((string) ($_POST['newlabel'] ?? ''));
            if ($newLabel === '' || strlen($newLabel) > 128 || !preg_match('/^[A-Za-z0-9_.-]+$/', $newLabel)) {
                $errorMessage = 'Use 1–128 letters, numbers, dots, underscores, or hyphens for the label.';
            } elseif (array_key_exists($newLabel, $translations)) {
                $errorMessage = 'That translation label already exists.';
            } else {
                $translations[$newLabel] = $newLabel;
                if (language_editor_save($sellang, $translations, $errorMessage)) {
                    $notice = text('add_new_label') . ': ' . $newLabel;
                }
            }
        }
    }
}

$translations = language_editor_load($sellang);
$translationCount = count($translations);
if ($translationCount > 0 && $offset >= $translationCount) {
    $offset = max(0, (int) (floor(($translationCount - 1) / $pageSize) * $pageSize));
}
$visibleTranslations = array_slice($translations, $offset, $pageSize, true);
$pageCount = max(1, (int) ceil($translationCount / $pageSize));
$currentPage = (int) floor($offset / $pageSize) + 1;

$breadcrumbs[] = buildLink('../administration/admin.php', text('administration'));
$breadcrumbs[] = text('edit_language');
$pageSection = 'admin';
require_once('../themes/' . THEME . '/header.php');
?>

<style>
    .language-editor { max-width: 1200px; margin: 0 auto 2rem; }
    .language-editor__hero { display: flex; justify-content: space-between; gap: 1rem; align-items: center; padding: 1.5rem; color: #fff; border-radius: 1rem; background: linear-gradient(135deg, #263e66, #287388); box-shadow: 0 14px 34px rgba(31, 55, 91, .16); }
    .language-editor__hero h1 { margin: 0; font-size: clamp(1.4rem, 3vw, 2rem); }
    .language-editor__hero p { margin: .35rem 0 0; color: rgba(255, 255, 255, .78); }
    .language-editor__count { min-width: 90px; padding: .75rem 1rem; text-align: center; border: 1px solid rgba(255, 255, 255, .24); border-radius: .8rem; background: rgba(255, 255, 255, .1); }
    .language-editor__count strong { display: block; font-size: 1.35rem; }
    .language-toolbar { display: grid; grid-template-columns: minmax(240px, 1fr) minmax(300px, 1.4fr); gap: 1rem; margin: 1rem 0; }
    .language-toolbar__card { padding: 1rem; border: 1px solid #dce5ef; border-radius: .85rem; background: #fff; }
    .translation-card { overflow: hidden; border: 1px solid #dce5ef; border-radius: 1rem; background: #fff; box-shadow: 0 10px 28px rgba(34, 49, 72, .07); }
    .translation-card__header { display: flex; flex-wrap: wrap; justify-content: space-between; gap: .75rem; align-items: center; padding: 1rem 1.2rem; border-bottom: 1px solid #e6edf5; }
    .translation-card__header h2 { margin: 0; font-size: 1.1rem; }
    .translation-key { max-width: 330px; color: #3e526c; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .82rem; overflow-wrap: anywhere; }
    .translation-input { min-width: 320px; }
    .translation-actions { display: flex; flex-wrap: wrap; justify-content: space-between; gap: .75rem; padding: 1rem 1.2rem; border-top: 1px solid #e6edf5; background: #f9fbfd; }
    @media (max-width: 760px) {
        .language-editor__hero { align-items: flex-start; }
        .language-toolbar { grid-template-columns: 1fr; }
        .translation-input { min-width: 220px; }
    }
</style>

<main class="language-editor">
    <header class="language-editor__hero">
        <div>
            <h1><i class="fa-solid fa-language me-2"></i><?php echo htmlspecialchars(text('edit_language'), ENT_QUOTES, 'UTF-8'); ?></h1>
            <p><?php echo htmlspecialchars(text('language_intro'), ENT_QUOTES, 'UTF-8'); ?></p>
        </div>
        <div class="language-editor__count"><strong><?php echo $translationCount; ?></strong><?php echo htmlspecialchars(text('Phrases'), ENT_QUOTES, 'UTF-8'); ?></div>
    </header>

    <?php if ($notice !== ''): ?><div class="alert alert-success mt-3"><i class="fa-solid fa-circle-check me-2"></i><?php echo htmlspecialchars($notice, ENT_QUOTES, 'UTF-8'); ?></div><?php endif; ?>
    <?php if ($errorMessage !== ''): ?><div class="alert alert-danger mt-3"><i class="fa-solid fa-triangle-exclamation me-2"></i><?php echo htmlspecialchars($errorMessage, ENT_QUOTES, 'UTF-8'); ?></div><?php endif; ?>

    <section class="language-toolbar">
        <form method="GET" action="../administration/edit_language.php" class="language-toolbar__card">
            <label class="form-label fw-semibold" for="languageSelection"><?php echo htmlspecialchars(text('Choose_Language'), ENT_QUOTES, 'UTF-8'); ?></label>
            <select class="form-select" id="languageSelection" name="language" onchange="this.form.submit()">
                <?php asort($allowedLanguages); foreach ($allowedLanguages as $key => $language): ?>
                    <option value="<?php echo htmlspecialchars($key, ENT_QUOTES, 'UTF-8'); ?>"<?php echo $sellang === $key ? ' selected' : ''; ?>><?php echo htmlspecialchars($language, ENT_QUOTES, 'UTF-8'); ?></option>
                <?php endforeach; ?>
            </select>
        </form>

        <form method="POST" action="../administration/edit_language.php" class="language-toolbar__card">
            <input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8'); ?>">
            <input type="hidden" name="language" value="<?php echo htmlspecialchars($sellang, ENT_QUOTES, 'UTF-8'); ?>">
            <input type="hidden" name="offset" value="<?php echo $offset; ?>">
            <label class="form-label fw-semibold" for="newLanguageLabel"><?php echo htmlspecialchars(text('add_new_label'), ENT_QUOTES, 'UTF-8'); ?></label>
            <div class="input-group">
                <input class="form-control" id="newLanguageLabel" name="newlabel" maxlength="128" placeholder="example_label" required>
                <button class="btn btn-primary" type="submit" name="action" value="add"><i class="fa-solid fa-plus me-1"></i><?php echo htmlspecialchars(text('add_label'), ENT_QUOTES, 'UTF-8'); ?></button>
            </div>
        </form>
    </section>

    <form method="POST" action="../administration/edit_language.php" class="translation-card">
        <input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8'); ?>">
        <input type="hidden" name="language" value="<?php echo htmlspecialchars($sellang, ENT_QUOTES, 'UTF-8'); ?>">
        <input type="hidden" name="offset" value="<?php echo $offset; ?>">

        <div class="translation-card__header">
            <h2><?php echo htmlspecialchars(text('Phrases'), ENT_QUOTES, 'UTF-8'); ?> <span class="badge text-bg-light border ms-1"><?php echo htmlspecialchars($allowedLanguages[$sellang], ENT_QUOTES, 'UTF-8'); ?></span></h2>
            <nav aria-label="Translation pages">
                <ul class="pagination pagination-sm mb-0">
                    <?php for ($page = 1; $page <= $pageCount; $page++): $pageOffset = ($page - 1) * $pageSize; ?>
                        <li class="page-item<?php echo $page === $currentPage ? ' active' : ''; ?>"><a class="page-link" href="../administration/edit_language.php?language=<?php echo urlencode($sellang); ?>&amp;offset=<?php echo $pageOffset; ?>"><?php echo $page; ?></a></li>
                    <?php endfor; ?>
                </ul>
            </nav>
        </div>

        <div class="table-responsive">
            <table class="table table-hover align-middle mb-0">
                <thead class="table-light"><tr><th style="width:42px"><span class="visually-hidden"><?php echo htmlspecialchars(text('delete'), ENT_QUOTES, 'UTF-8'); ?></span></th><th><?php echo htmlspecialchars(text('Label'), ENT_QUOTES, 'UTF-8'); ?></th><th><?php echo htmlspecialchars(text('Translation'), ENT_QUOTES, 'UTF-8'); ?></th></tr></thead>
                <tbody>
                    <?php $rowId = 0; foreach ($visibleTranslations as $key => $value): ?>
                        <tr>
                            <td><input class="form-check-input" type="checkbox" name="remove[]" value="<?php echo htmlspecialchars($key, ENT_QUOTES, 'UTF-8'); ?>" aria-label="<?php echo htmlspecialchars(text('delete') . ' ' . $key, ENT_QUOTES, 'UTF-8'); ?>"></td>
                            <td class="translation-key"><?php echo htmlspecialchars($key, ENT_QUOTES, 'UTF-8'); ?><input type="hidden" name="key[<?php echo $rowId; ?>]" value="<?php echo htmlspecialchars($key, ENT_QUOTES, 'UTF-8'); ?>"></td>
                            <td><input class="form-control translation-input" name="translation[<?php echo $rowId; ?>]" value="<?php echo htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); ?>"></td>
                        </tr>
                    <?php $rowId++; endforeach; ?>
                </tbody>
            </table>
        </div>

        <div class="translation-actions">
            <button class="btn btn-outline-danger" type="submit" name="action" value="delete" onclick="return confirm(<?php echo htmlspecialchars(json_encode(text('delete_following')), ENT_QUOTES, 'UTF-8'); ?>);"><i class="fa-regular fa-trash-can me-1"></i><?php echo htmlspecialchars(text('delete'), ENT_QUOTES, 'UTF-8'); ?></button>
            <button class="btn btn-primary px-4" type="submit" name="action" value="save"><i class="fa-regular fa-floppy-disk me-2"></i><?php echo htmlspecialchars(text('save_translation'), ENT_QUOTES, 'UTF-8'); ?></button>
        </div>
    </form>
</main>

<?php require_once('../themes/' . THEME . '/footer.php'); ?>
